name: Quick Report
description: "A minimal template for fast and straightforward reports."
title: "[Quick Report]:"
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        > **Note:**
        > This template is intended for non-developers who need a quick, straightforward way to report issues.  
        > Developers or those with detailed technical info should use an alternative template.  
        > 
        > **key points:**
        > - **Quick & Simple:** Only the essentials are required.  
        > - **User-Friendly:** Perfect for non-tech users.  
        > - **Minimal Steps:** Ensures a fast and easy reporting process.  
        > - **Initial Triage:** Captures key info for follow-up.  
        > - **Flexible:** Suitable for any type of issue.  

  - type: markdown
    attributes:
      value: |

        **Thank you** for your time! Your effort is greatly appreciated.

        Please fill out the section below with the **essential details** for your report.  

  - type: dropdown
    id: heading
    attributes:
      label: "Quick Report, Issue Submission:"
      description: "You are about to create an issue report for the project. This issue report will be publicly visible to developers and users alike. Please double-check your submission to ensure accuracy and that you have not clicked it accidentally."
      options:
        - "Yes, I'm aware that this issue will be public"
        - "I'm aware this will be public, but I'd like to have a private discussion"
    validations:
      required: true

  - type: checkboxes
    id: duplicate-check
    attributes:
      label: "Duplicate Check:"
      description: Before submitting, verify that Someone haven't already reported this issue by checking both "open" AND "closed" issues.
      options:
        - label: "I have reviewed existing issues and confirmed this report is unique."
          required: false

  - type: input
    id: Issue-title
    attributes:
      label: "Issue Title:"
      description: "Provide a short and clear title for the issue."
      placeholder: Brief issue summary

  - type: textarea
    id: bullet-details
    attributes:
      label: "Issue Description:"
      description: "Describe the issue in details. Use bullet points where possible. Avoid large text blocks, attach relevant content using the button below."
      placeholder: |
        - First key point
        - Second key point
        - Affected Component
        - Additional details

        - What did you expect to happen?
        - What actually happened instead?
        - steps that lead to this?

  - type: dropdown
    id: work-on-issue
    attributes:
      label: "Are you planning to work on this issue?"
      description: "Let us know if you intend to address this issue yourself."
      options:
        - "Yes, I will work on this issue."
        - "No, I am not able to work on this issue."
        - "Not sure yet."

  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct:"
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Himanshu-Parangat/cnss/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
