name: Bug Report
description: "A template for reporting bugs or something that doesn't seem right."
title: "[Bug]:"
labels: ["needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        > **Note:**
        > - For **bugs/issues/unexpected Behavior:** Use this template.
        > - For **critical security issues:** Contact privately.

  - type: markdown
    attributes:
      value: |

        **Thank you** for your time! Your effort is greatly appreciated.

        Please fill out the section below with the **essential details** for your report.

  - type: dropdown
    id: heading
    attributes:
      label: "Bug Report, Issue Submission:"
      description: "You are about to create an issue report for the project. This issue report will be publicly visible to developers and users alike. Please double-check your submission to ensure accuracy and that you have not clicked it accidentally."
      options:
        - "Yes, I'm aware that this issue will be public"
        - "I'm aware this will be public, but I'd like to have a private discussion"
    validations:
      required: true

  - type: checkboxes
    id: duplicate-check
    attributes:
      label: "Duplicate Check:"
      description: Before submitting, verify that Someone haven't already reported this issue by checking both "open" AND "closed" issues.
      options:
        - label: "I have reviewed existing issues and confirmed this report is unique."
          required: false

  - type: dropdown
    id: regression
    attributes:
      label: Is this a regression?
      description: |
        A regression means something that previously worked has stopped working.
        Identifying regressions helps prioritize fixes.
      multiple: false
      options:
        - "Yes, it worked before but broke after a recent change"
        - "I'm unsure if this worked before"
        - "No, this bug has always existed"
        - "No, this issue is with a feature that was recently introduced"
        - "No, this is a documentation issue"
        - "I don’t know, I’m new to the project"
    validations:
      required: true

  - type: input
    id: issue-scope
    attributes:
      label: "Where did you find it?"
      description: |
        Please specify where you observed the issue. This could be a file path, directory, UI element, or any specific location within the project.
        this will help diagnose the problem faster and narrow down scope.

        > **For example:**
        > - `cnss/testing-env/server/main.go`
        > - `Settings page > Config section`
        > - `API response from /headers endpoint`

      placeholder: "In dashboard ui button x"
    validations:
      required: true

  - type: input
    id: issue-title
    attributes:
      label: "Issue Title:"
      description: "Provide a short and clear title for the issue."
      placeholder: Brief issue summary

  - type: textarea
    id: bullet-details
    attributes:
      label: "Issue Description:"
      description: "Describe the issue in details. Use bullet points where possible. Avoid large text blocks, attach relevant content using the button below."
      placeholder: |
        - First key point
        - Second key point
        - Affected Component
        - Additional details

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior:"
      description: Describe what you expected to happen.
      placeholder: |
        I expected [the feature] to [action] and [result].
        For example: I expected the page to load quickly and display the correct information.
    validations:
      required: false

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior:"
      description: Describe what actually happened.
      placeholder: |
        Instead, [the feature] [action] and [result].
        For example: Instead, the page took a long time to load and displayed an error message.
    validations:
      required: false

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce:"
      description: |
        List the exact steps needed to reproduce the issue. Be as specific as possible, including:
          * What browser/device/tool you are using
          * What environment you are on?
          * Any specific actions you took before encountering the issue
      placeholder: |
        1. start the docker
        2. Curl: 172.16.0.3:8080
        3. pass it in jq
        4. Observe the issue
    validations:
      required: false


  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed Solution: (Optional)"
      description: |
        If you have any ideas about how to fix the issue, please share them here. This is optional.  Even if you're not sure, any insights you have might be helpful.
      placeholder: |
        I suspect the problem might be related to [area of the code/system] and could potentially be fixed by [your suggested approach].
    validations:
      required: false


  - type: dropdown
    id: work-on-issue
    attributes:
      label: "Are you planning to work on this issue?"
      description: "Let us know if you intend to address this issue yourself."
      options:
        - "Yes, I will work on this issue."
        - "No, I am not able to work on this issue."
        - "Not sure yet."

  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct:"
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Himanshu-Parangat/cnss/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
