blank_issues_enabled: true
contact_links:
  - name: "CODE OF CONDUCT"
    url: "https://github.com/Himanshu-Parangat/cnss/blob/main/CODE_OF_CONDUCT.md"
    about: "please follow code of conduct & maintain decorum."
