version: "3.8"

services:

  application:
    build:
      context: ../testing-env/application/
      dockerfile: Dockerfile
    container_name: application
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
    - lab-network


  server:
    build:
      context: ../testing-env/server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8090:8090"
    restart: unless-stopped
    networks:
    - lab-network

networks:
  lab-network:
    driver: bridge
