services:

  application:
    image: application
    build:
      context: ../testing-env/application/
      dockerfile: Dockerfile
    container_name: application
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      lab-network:
        ipv4_address: 172.16.0.2


  server:
    image: server
    build:
      context: ../testing-env/server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8090:8090"
    restart: unless-stopped
    networks:
      lab-network:
        ipv4_address: 172.16.0.3

networks:
  lab-network:
    driver: bridge
    name: lab-network
    ipam:
      config:
       - subnet: 172.16.0.0/29
