name: Build All Artifacts
on:
  workflow_dispatch:
jobs:
  build-all-components:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: prod

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: false
          check-latest: true

      - name: Detect Go Modules Needing Cache
        id: gosum-cache-check
        shell: bash
        run: |
          declare -A modules=(
            ["firewall/reverseProxy"]="reverseProxy"
            ["firewall/waf"]="waf"
            ["testing-env/server"]="server"
            ["testing-env/application"]="application"
            ["testing-env/simulator"]="simulator"
          )
          
          echo "Checking for Go modules..."
          for path in "${!modules[@]}"; do
            name="${modules[$path]}"
            
            if [ -f "$path/go.sum" ]; then
              echo "$name=true" >> $GITHUB_OUTPUT
              echo -e "::notice:: \e[32mCache needed for module $name for $path/go.mod\e[0m"
            else
              echo "$name=false" >> $GITHUB_OUTPUT
              echo -e "::warning:: \e[35mIgnoring module $name for non-existing $path/go.mod\e[0m"
            fi
          done


      - name: Cache Go modules - Reverse Proxy
        if: steps.gosum-cache-check.outputs.reverseProxy == 'true'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/firewall/reverseProxy/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-


      - name: Cache Go modules - WAF
        if: steps.gosum-cache-check.outputs.waf == 'true'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/firewall/waf/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-


      - name: Cache Go modules - Server
        if: steps.gosum-cache-check.outputs.server == 'true'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/testing-env/server/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-


      - name: Cache Go modules - Application
        if: steps.gosum-cache-check.outputs.application == 'true'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/testing-env/application/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-


      - name: Cache Go modules - Simulator
        if: steps.gosum-cache-check.outputs.simulator == 'true'
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/testing-env/simulator/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-


      - name: Display Build Help message
        run: make help


      - name: Build All Components
        run: make build-all


      - name: Upload Built Binaries
        uses: actions/upload-artifact@v4
        with:
          name: built-binaries
          path: bin/*
          if-no-files-found: error
          retention-days: 1
