name: Build All Artifacts
on:
  workflow_dispatch:
jobs:
  build-all-components:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: prod

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: false
          check-latest: true
